package com.aura.aura_ui.presentation.screens

import android.annotation.SuppressLint
import android.webkit.WebView
import android.widget.Toast
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.PictureAsPdf
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.viewinterop.AndroidView
import com.aura.aura_ui.mcp.log.AgentRunLogger
import com.aura.aura_ui.mcp.log.LiveConversationLogger
import com.aura.aura_ui.mcp.log.McpLogPdfExporter
import com.aura.aura_ui.mcp.log.McpSessionStore
import com.aura.aura_ui.mcp.log.SessionHtmlRenderer
import com.aura.aura_ui.mcp.log.SessionLog
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

/**
 * Full-screen detail of a single session (MCP **or** on-device agent) rendered as
 * a LangSmith-style HTML trace in a WebView: chronological tool calls + LLM
 * round-trips, collapsible prompts, token counts, and tap/swipe-annotated
 * screenshots. PDF export bundles the same content for off-device sharing.
 *
 * The HTML is generated by [SessionHtmlRenderer] from `metadata.json` (the
 * canonical record) and loaded with `baseUrl = file://<sessionDir>/` so the
 * relative screenshot `<img>` paths resolve.
 */
/**
 * Detail dispatcher: on-device **agent** runs get the native Trace-v2 screen
 * ([AgentTraceScreen]); external **MCP** sessions keep the HTML WebView below.
 */
@Composable
fun McpSessionDetailScreen(
    sessionId: String,
    onNavigateBack: () -> Unit,
) {
    val context = LocalContext.current
    val store = remember { McpSessionStore(context) }
    // On-device sessions — agent runs AND conversations — get the native trace screen; only an
    // external MCP client's session still uses the HTML WebView. A conversation that starts a
    // phone task now shares ONE session with it, so routing on source would otherwise send a log
    // containing both speech and tool calls to whichever renderer knew about half of it.
    var native by remember(sessionId) { mutableStateOf<Boolean?>(null) }
    LaunchedEffect(sessionId) {
        native = withContext(Dispatchers.IO) {
            store.readSession(sessionId)?.source in setOf(
                AgentRunLogger.SOURCE_AGENT,
                LiveConversationLogger.SOURCE_LIVE,
            )
        }
    }
    when (native) {
        null -> Box(Modifier.fillMaxSize(), Alignment.Center) { CircularProgressIndicator() }
        true -> AgentTraceScreen(sessionId, onNavigateBack)
        false -> McpWebViewDetailScreen(sessionId, onNavigateBack)
    }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
private fun McpWebViewDetailScreen(
    sessionId: String,
    onNavigateBack: () -> Unit,
) {
    val context = LocalContext.current
    val store = remember { McpSessionStore(context) }
    val exporter = remember { McpLogPdfExporter(context) }
    val scope = rememberCoroutineScope()

    var session by remember(sessionId) { mutableStateOf<SessionLog?>(null) }
    var html by remember(sessionId) { mutableStateOf<String?>(null) }
    var baseUrl by remember(sessionId) { mutableStateOf<String?>(null) }
    var exporting by remember { mutableStateOf(false) }

    LaunchedEffect(sessionId) {
        withContext(Dispatchers.IO) {
            val s = store.readSession(sessionId)
            val dir = store.sessionDir(sessionId)
            session = s
            if (s != null && dir != null) {
                html = runCatching { SessionHtmlRenderer.render(s, dir) }.getOrNull()
                baseUrl = "file://${dir.absolutePath}/"
            }
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Session detail") },
                navigationIcon = {
                    IconButton(onClick = onNavigateBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back")
                    }
                },
                actions = {
                    IconButton(
                        enabled = !exporting && session != null,
                        onClick = {
                            exporting = true
                            scope.launch {
                                val file = withContext(Dispatchers.IO) {
                                    runCatching { exporter.export(sessionId) }.getOrNull()
                                }
                                exporting = false
                                Toast.makeText(
                                    context,
                                    file?.let { "PDF saved to ${it.absolutePath}" } ?: "PDF export failed",
                                    Toast.LENGTH_LONG,
                                ).show()
                            }
                        },
                    ) {
                        Icon(Icons.Filled.PictureAsPdf, contentDescription = "Export PDF")
                    }
                },
            )
        },
    ) { padding ->
        val content = html
        when {
            session == null && html == null ->
                Box(Modifier.fillMaxSize().padding(padding), Alignment.Center) {
                    CircularProgressIndicator()
                }
            content == null ->
                Box(Modifier.fillMaxSize().padding(padding), Alignment.Center) {
                    Text("Session not found.")
                }
            else -> SessionWebView(
                html = content,
                baseUrl = baseUrl,
                modifier = Modifier.fillMaxSize().padding(padding),
            )
        }
    }
}

@SuppressLint("SetJavaScriptEnabled")
@Composable
private fun SessionWebView(html: String, baseUrl: String?, modifier: Modifier = Modifier) {
    AndroidView(
        modifier = modifier,
        factory = { ctx ->
            WebView(ctx).apply {
                settings.javaScriptEnabled = true        // collapse/expand toggles
                settings.allowFileAccess = true          // load screenshots via file://
                settings.allowFileAccessFromFileURLs = true
                settings.loadWithOverviewMode = true
                settings.useWideViewPort = false
                setBackgroundColor(android.graphics.Color.parseColor("#0b0f14"))
            }
        },
        update = { web ->
            web.loadDataWithBaseURL(baseUrl, html, "text/html", "UTF-8", null)
        },
    )
}
