// Builds aura-android-use-website/privacy.html from the app's own legal text, so the website and the
// in-app Privacy / Terms screens can never say different things.
// - Reads: aura-android/app/src/main/java/com/aura/aura_ui/presentation/screens/legal/LegalCopy.kt
// - Writes: aura-android-use-website/privacy.html (served at /privacy; the terms are at /privacy#terms)
// - Change together: run `node scripts/gen_legal_page.mjs` after every edit to LegalCopy.kt and commit both.
// - Fails: throws if LegalCopy.kt no longer has the PRIVACY / TERMS strings or the LICENSES list.
import { readFileSync, writeFileSync } from 'node:fs';

const ROOT = new URL('..', import.meta.url);
const kt = readFileSync(new URL('aura-android/app/src/main/java/com/aura/aura_ui/presentation/screens/legal/LegalCopy.kt', ROOT), 'utf8').replace(/\r\n/g, '\n');

const email = kt.match(/CONTACT_EMAIL = "([^"]+)"/)[1];
const text = (name) => {
  const m = kt.match(new RegExp(`val ${name} = """\\n([\\s\\S]*?)"""`));
  if (!m) throw new Error(`LegalCopy.kt: no ${name} string`);
  return m[1].replaceAll('$CONTACT_EMAIL', email).trim();
};
const licences = [...kt.matchAll(/^\s*"([^"]+)" to "([^"]+)",?$/gm)].map((m) => [m[1], m[2]]);
if (!licences.length) throw new Error('LegalCopy.kt: no LICENSES entries');

const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const linkify = (s) => s.replace(esc(email), `<a href="mailto:${email}">${email}</a>`);

// The Kotlin text is plain: blocks split by blank lines, a short first line is a heading,
// "• " starts a bullet and indented lines continue it.
function render(src, id) {
  const [title, updated, ...rest] = src.split('\n');
  const blocks = rest.join('\n').trim().split(/\n\s*\n/);
  let html = `<section id="${id}"><h1>${esc(title.replace(/^AURA — /, ''))}</h1><p class="upd">${esc(updated)}</p>`;
  for (const b of blocks) {
    const lines = b.split('\n');
    if (lines.length > 1 && lines[0].length < 60 && !/[.,:;]$/.test(lines[0]) && !lines[0].startsWith('•')) {
      html += `<h2>${esc(lines.shift())}</h2>`;
    }
    const items = [];
    for (const l of lines) {
      if (l.startsWith('• ')) items.push({ bullet: true, t: l.slice(2) });
      else if (items.length && (items.at(-1).bullet ? /^\s/.test(l) : true)) items.at(-1).t += ' ' + l.trim();
      else items.push({ bullet: false, t: l.trim() });
    }
    let ul = '';
    for (const it of items) {
      const t = linkify(esc(it.t));
      if (it.bullet) ul += `<li>${t}</li>`;
      else { if (ul) { html += `<ul>${ul}</ul>`; ul = ''; } html += `<p>${t}</p>`; }
    }
    if (ul) html += `<ul>${ul}</ul>`;
  }
  return html + '</section>';
}

const page = `<!DOCTYPE html>
<!-- Generated by scripts/gen_legal_page.mjs from LegalCopy.kt. Don't edit by hand. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>Privacy and Terms · AURA</title>
<meta name="description" content="AURA's privacy policy and terms of service: the same text the app shows.">
<link rel="canonical" href="https://aura-android-use.vercel.app/privacy">
<link rel="icon" href="/favicon.ico" sizes="48x48">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<meta property="og:image" content="https://aura-android-use.vercel.app/og.png">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Doto:wght@700..900&family=Geist:wght@400..600&family=Geist+Mono:wght@400..500&display=swap" rel="stylesheet">
<script>try{var t=localStorage.getItem('aura-theme');if(!t)t=matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';document.documentElement.setAttribute('data-theme',t);}catch(e){document.documentElement.setAttribute('data-theme','light');}</script>
<style>
:root{--paper:#E7E9EC;--ink:#0B0C0F;--ink2:#4C5058;--line:rgba(11,12,15,.15);--chip:rgba(11,12,15,.055);--logo:none;--hdr:rgba(231,233,236,.78);color-scheme:light}
@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){--paper:#000;--ink:#F3F4F6;--ink2:#9CA1AA;--line:rgba(255,255,255,.16);--chip:rgba(255,255,255,.07);--logo:invert(1);--hdr:rgba(0,0,0,.72);color-scheme:dark}}
:root[data-theme="dark"]{--paper:#000;--ink:#F3F4F6;--ink2:#9CA1AA;--line:rgba(255,255,255,.16);--chip:rgba(255,255,255,.07);--logo:invert(1);--hdr:rgba(0,0,0,.72);color-scheme:dark}
html{background:var(--paper)}
body{margin:0;background:var(--paper);color:var(--ink);font-family:Geist,ui-sans-serif,system-ui,sans-serif;-webkit-font-smoothing:antialiased;line-height:1.6}
a{color:var(--ink);text-underline-offset:3px}
header{position:sticky;top:0;z-index:5;background:var(--hdr);backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px);border-bottom:1px solid var(--line)}
header div{max-width:760px;margin:0 auto;height:60px;padding:0 16px;display:flex;align-items:center;gap:16px;font-size:14px}
header a{text-decoration:none}
.brand{display:flex;align-items:center;gap:9px;font-weight:600;font-size:16px;margin-right:auto}
.brand img{filter:var(--logo);display:block}
main{max-width:760px;margin:0 auto;padding:24px 16px 80px}
nav.toc{display:flex;flex-wrap:wrap;gap:8px;margin:8px 0 8px}
nav.toc a{font:500 12px 'Geist Mono',monospace;padding:6px 12px;border-radius:999px;border:1px solid var(--line);text-decoration:none}
nav.toc a:hover{background:var(--chip)}
section{padding-top:32px;scroll-margin-top:60px}
h1{font-family:Doto,monospace;font-weight:900;font-size:clamp(36px,8vw,56px);line-height:1;margin:0}
.upd{font:12px 'Geist Mono',monospace;color:var(--ink2);margin:12px 0 0}
h2{font-size:18px;margin:32px 0 6px}
p,li{font-size:16px;color:var(--ink)}
p{margin:0 0 12px}
ul{margin:0 0 12px;padding-left:20px}
li{margin-bottom:6px}
.note{font-size:14px;color:var(--ink2);border:1px solid var(--line);border-radius:14px;padding:14px 16px;margin:24px 0 0}
table{border-collapse:collapse;width:100%;font-size:15px}
td{border-top:1px solid var(--line);padding:8px 0}
td+td{color:var(--ink2);text-align:right}
footer{border-top:1px solid var(--line);padding:24px 16px;font:11.5px 'Geist Mono',monospace;color:var(--ink2);text-align:center}
</style>
</head>
<body>
<header><div><a class="brand" href="/"><img src="/media/aura_logo_mono.png" alt="" width="24" height="24">AURA</a><a href="/">← Back to the site</a></div></header>
<main>
<nav class="toc" aria-label="On this page"><a href="#privacy">Privacy</a><a href="#terms">Terms</a><a href="#licences">Open-source licences</a></nav>
<p class="note">This is the same text the app shows under Settings → Privacy &amp; Data. AURA itself is open source under the
<a href="https://github.com/Dinesh210805/aura-android-use/blob/main/LICENSE">GNU AGPL-3.0</a>, so you can also read exactly what the code does.</p>
${render(text('PRIVACY'), 'privacy')}
${render(text('TERMS'), 'terms')}
<section id="licences"><h2>Open-source licences</h2><p>AURA is built on these projects:</p><table>${licences.map(([n, l]) => `<tr><td>${esc(n)}</td><td>${esc(l)}</td></tr>`).join('')}</table></section>
</main>
<footer>AURA · <a href="mailto:${email}">${email}</a></footer>
</body>
</html>
`;
writeFileSync(new URL('aura-android-use-website/privacy.html', ROOT), page);
console.log('wrote aura-android-use-website/privacy.html');
